= Gradleプロジェクトの作成

Gradleには https://docs.gradle.org/current/userguide/build_init_plugin.html[Build Init Plugin] というGradleプロジェクトを生成するプラグインがあります。(詳しくは <<引用>> 参照)

`mvn archetype:generate` に比べて圧倒的にテンプレートが少ないというより、機能不足すぎるわけですが、最低限のプロジェクト構成を生成することができます。

なお、現在incubating(先進的)な機能なため、今後テンプレートタイプが詳細に指定できるようになるかもしれないし、taichiさんのQiitaの記事 http://qiita.com/taichi@github/items/a4caab3a31dd5949a045[Gradle で initタスクをカスタマイズする方法] にあるようにオレオレテンプレートを作る方法が一般的になるかもしれません。

とりあえず、プロジェクトを作るのにいちいち `mkdir` コマンドを叩くのが面倒なときに使うとよいでしょう。

== 演習1 typeの指定なしでプロジェクトをinitする

`java-projects/init-project/no-type` ディレクトリーに移動して、次のコマンドを入力してください。

[source]
----
$ gradle init
----

'''

次のようなディレクトリーが作成されます。

[source]
----
.
├── build.gradle
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradlew
├── gradlew.bat
└── settings.gradle
----

なお、この `init` タスクは

* コメントアウトされたスクリプトしか書かれていない `build.gradle`
* プロジェクトの名前を定義しただけの `settings.gradle`
* 使っているバージョンのwrapperファイル

という、あまり意味のないものだけが生成されるちょっと悲しい機能です。

= `type` オプションを使って、言語別のテンプレートプロジェクトを生成する

`init` タスクに対してオプションを指定せずに作成した場合、上記のようにほとんど何の機能も持たないプロジェクトが生成されてしまいます。

そこで、Gradleでは下記の言語に合わせた標準的なディレクトリー構成を作るオプションを `init` タスクに提供しています。

* Java
* Groovy
* Scala

これらの標準的なプロジェクト構成は `init` タスクの `--type` オプションによって指定することによって作成することができます。
それではこれらの標準的なプロジェクト構成をこのあとの演習で作成していきましょう。

== 演習2 java library type

まずはJavaプロジェクトの標準的なディレクトリー構成を生成する方法を実際にやってみます。

`java-projects/init-project/java-lib` ディレクトリーに移動してください。

次のコマンドを入力してください。

[source]
----
$ gradle init --type java-library
----

'''

次のようなディレクトリーが作成されます。

[source]
----
.
├── build.gradle
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradlew
├── gradlew.bat
├── settings.gradle
└── src
    ├── main
    │   └── java
    │       └── Library.java
    └── test
        └── java
            └── LibraryTest.java
----

この `init` で生成されるプロジェクトは次のようなものです。

* `java` プラグインが適用されている
* レポジトリーに `jcenter` が指定されている
* `slf4j` の `1.7.12` に `compile` スコープで依存している
* `junit` の `4.12` に `testCompile` スコープで依存している

また、最初に紹介したプロジェクトの基本構成が自動的に生成されます。

最初のtype指定なしよりはまともそうなプロジェクトですね。

'''

== 演習3 groovy library type

次はGroovyタイプのテンプレートを作成します。

`javajo-gradle/java-projects/init-project/groovy-lib` ディレクトリーに移動してください。

次のコマンドを入力してください。

[source]
----
$ gradle init --type groovy-library
----

'''

次のようなディレクトリーが作成されます。

[source]
----
.
├── build.gradle
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradlew
├── gradlew.bat
├── settings.gradle
└── src
    ├── main
    │   └── groovy
    │       └── Library.groovy
    └── test
        └── groovy
            └── LibraryTest.groovy
----

この `init` で生成されるプロジェクトは次のようなものです。

* `groovy` プラグインが適用されている
* レポジトリーに `jcenter` が指定されている
* Groovyに `groovy-all` の `2.4.4` が指定されている
* テスト用のライブラリーに `spock` の `1.0-groovy-2.4` が用いられている
* テスト用のライブラリーに `junit` の `4.12` が用いられている(transitive dependencyで実は指定する必要がないのは内緒だよ)

== 演習4 Scala library type

Gradleはsbtほど厳密ではない(らしい)けど、Scalaプロジェクトのビルドも可能です。

ということで、Scalaタイプのプロジェクトの `init` タスクもあります。

`javajo-gradle/java-projects/init-project/scala-lib` ディレクトリーに移動してください。

次のコマンドを入力してください。

[source]
----
$ gradle init --type scala-library
----

'''

次のようなディレクトリーが作成されます。

[source]
----
.
├── build.gradle
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradlew
├── gradlew.bat
├── settings.gradle
└── src
    ├── main
    │   └── scala
    │       └── Library.scala
    └── test
        └── scala
            └── LibrarySuite.scala
----

この `init` タスクで生成されるプロジェクトは次のようなものです。

* `scala` プラグインが適用されている
* レポジトリーに `jcenter` が指定されている
* Scalaのバージョンは `2.11.7`
* テスト用のライブラリーに `scalatest_2.11` のバージョン `2.2.5` が用いられている
* テスト用のライブラリーに `junit` の `4.12` が用いられている
* テストのランタイムライブラリーに `scala-xml_2.11` のバージョン `1.0.5` が用いられている

'''

= テンプレート作成後

混みいったプロジェクトでなければ、次のような作業の後にプロジェクトの作成がスムーズに行きます。

* プロジェクトの情報を `build.gradle` に入力。
* `gradle.properties` にデーモン利用フラグを設定する。
* いらないファイル `Library.(java|groovy|scala)` を削除する
* パッケージ階層を構築
* お好みの依存ライブラリーを設定する
* お好みのプラグインを適用する

== 引用

.https://docs.gradle.org/current/userguide/build_init_plugin.html[Build Init Plugin] より引用
[quote, 'https://docs.gradle.org/current/userguide/build_init_plugin.html[Build Init Plugin]']
====
The Build Init plugin is an automatically applied plugin, which means you do not need to apply it explicitly. To use the plugin, simply execute the task named init where you would like to create the Gradle build. There is no need to create a “stub” build.gradle file in order to apply the plugin.
====

.意訳
====
init プラグインは自動的に適用されるプラグインです。つまり明示的に適用すると宣言しなくて良いのです。このプラグインを使うには、Gradleプロジェクトを作りたいディレクトリーで init タスクを実行すればよいだけです。これを使うには、事前に build.gradle ファイルを用意する必要はありません。
====

Gradleは単なるタスク実行基盤であって、プラグインを適用して初めてタスクやその他の便利な機能を利用することができます。 `build.gradle` ファイルのない状態においては、唯一 `Build init` プラグインのみが適用された状態になっています。
プラグインなどについては、この後に説明していきます。
