= アーカイビングタスク

成果物をzipファイルに固めるなどの処理はよく行われるタスクの一つです。

このセクションではzipにアーカイブする方法について学習します。

== `Zip` タスク

`Zip` タスクは `AbstractCopy` タスクを継承したタスクで、ほとんどのメソッドは `AbstractCopy` に由来するものです。したがって、 `Copy` と同じような操作を行うことができます。

.`Copy` タスクと異なる点
* アーカイブ名を設定する
* `into` の動作が `Copy` から想像できる動作とはことなる

== アーカイブ名を設定する

アーカイブ名を設定するための `Zip` タスクのプロパティとして以下のものが上げられます。

.`Zip` タスクのプロパティ
|===
|プロパティ名 |内容 |デフォルト値

|`baseName`
|アーカイブの基本名
|`project.archiveBaseName`(プロジェクト名)

|`appendix`
|アーカイブ名の補助的な名前(オプショナル)
|`null`

|`version`
|アーカイブのバージョン(オプショナル)
|`null`

|`classifier`
|アーカイブの識別名(オプショナル)
|`null`

|`extension`
|アーカイブの拡張子
|`zip`

|`archiveName`
|アーカイブ名
|`"${baseName}-${appendix}-${version}-${classifier}.${extension}"`

|`destinationDir`
|アーカイブファイルが生成されるディレクトリー
|`project.distsDir`(`build/distributions`)
|===

.`Zip` タスクの例
[source,groovy]
----
task zipServer(type: Zip) {
  from '../images/server'  /* <1> */
  baseName 'zip-server'  /* <2> */
  destinationDir = file("${buildDir}/server-image") /* <3> */
}
----
<1> アーカイブ対象のファイルを指定する
<2> アーカイブの基本名を設定する
<3> zipファイルの生成されるディレクトリーを設定する

=== 演習1

.上記の `zipServer` タスクを実行してください。
* 生成されたアーカイブのディレクトリーと名前を確認してください。
* 生成されたアーカイブを解凍して、内容物が指定されたファイルと同じであるか確認してください。

=== 演習2

.セクション1の演習6でコピーした内容と同様のファイルをアーカイブする `Zip` タスクを作成してください。
* 生成されるアーカイブの名前が `complex.zip` となるように設定してください。
* アーカイブが生成されるディレクトリーは `build/exercise2` となるように設定してください。

== `into` の動作

`into` を指定するとアーカイブ中のディレクトリーの位置が指定されます。生成されるアーカイブのディレクトリーではなくなるので注意してください。

.`into` を使った `Zip` タスクの例
[source,groovy]
----
/* into を使ってアーカイブ内のディレクトリーの位置を指定 */
task zipIntoDist(type: Zip) {
  from fileTree('../images')
  into 'dist'
  baseName = 'with-into'
}
/* into を使わない */
task zipWithoutInto(type: Zip) {
  from fileTree('../images')
  baseName = 'without-into'
}
----

=== 演習3

.上記の `zipIntoDist` および `zipWithoutInto` をそれぞれ実行した後に、それぞれを解凍してアーカイブ中の構造の様子を確認してください。
* `zipIntoDist` で生成されたzipファイルのルートに `dist` ディレクトリーがあることを確認してください。
* `zipWithoutInto` で生成されたzipファイルは `images` ディレクトリーと同じ構造になっていることを確認してください。

== 入力にタスクを指定する

2章のセクション4でタスクの `inputs` にタスクを指定できたように、 `Copy` および `Zip` でも `from` にタスクを渡すことができます。

=== 演習4

.次のようなテキストファイルを出力するタスクの成果物をzipに固めるタスクを作成してください。
* なお、出力するディレクトリーは `build/zip-langs` としてください。
* zipファイルの名前は `langs.zip` としてください。

.プログラミング言語名がファイル名であるテキストファイルを出力するタスク
[source,groovy]
----
task fiveLangs {
  def langs = [
    'Java', 'Groovy', 'Scala',
    'Kotlin', 'Clojure'
  ]
  def destDir = file("${buildDir}/langs")
  outputs.dir (destDir)
  doLast {
    if (!destDir.exists()) {
      destDir.mkdirs()
    }
    langs.each {
      file("${destDir}/${it}.txt").write(it, 'UTF-8')
    }
  }
}
----
