= `Jar` タスクの作り方

`copy-projects/jar` ディレクトリーに移動してください。

`Zip` タスクをほぼものにできたら、 `Jar` タスクをものにできたものと思ってもほとんどかまいません。

ほぼ唯一の違いは `manifest{}` ブロックの存在です。
(`destinationDir` がデフォルトで `libs` に設定されているという違いもある)

== Fat Jarを作ってみる

これはgoogleで検索すると、いくつも結果が出てくるものですが、 `Jar` タスクを理解するための最も簡単な題材です。

.Fat Jarを作るタスク
[source,groovy]
----
task fatJar(type: Jar) {
  from (configurations.runtime.findAll {
    !it.directory
  }.collect {
    zipTree(it)
  }) {
    exclude '**/META-INF/MANIFEST.MF'
  }
  destinationDir "${buildDir}/fat-jar"
  baseName = 'all-jars'
  manifest {
    attributes 'Created-By': "Gradle ${gradle.gradleVersion}",
        'Library-Version': version
  }
}
----

=== 演習1

上記の `fatJar` タスクを実行して、Fat Jarが作成されているか確認してください。また、作成されたjarファイル(実態はzipファイル)を解凍して、指定した通りのManifestファイルが作成されているか確認してください。

.`zipTree` とは？
[TIP]
====

zipにアーカイブされているファイルをあたかもファイルツリーのように扱えるようにする `project` のメソッドです。返されるのは `FileTree` インターフェースですので、必要になるまで中身が計算されることはありません。
また、zipファイルだけでなく、tarファイルにも対応している `tarTree` というメソッドもあります。

====

.`manifest{}` ブロック
[TIP]
====

`manifest{}` ブロック(オブジェクト)では次のようなことが可能です。


.`Manifest` インターフェースの主なメソッド
|===
|メソッド |引数 |内容

|`attributes`
|`Map<String, ?>`
|mainのアトリビュートに値を追加する。

|`attributes`
|`Map<String, ?>`, `String`
|指定したセクションのアトリビュートに値を追加する。

|`from`
|`Object...`
|指定されたマニフェストファイルをマージする。
|===

.`manifest{}` ブロックの利用例
[source,groovy]
----
zip {
  manifest {
    attributes 'Main-Class': 'javajo.sample.AppMain',
        'Created-By': "Gradle ${gradle.gradleVersion}"
  }
}
----

上記の `manifest{}` ブロックの記述で以下のような `MANIFEST.MF` ファイルが作成されます。

[source,text]
----
Manifest-Version: 1.0
Main-Class: javajo.sample.AppMain
Created-By: Gradle 2.7
----

====

=== 演習2

`copy-projects/jar` は `java` プラグインが適用されていて、依存ライブラリーを用いた簡単なJavaプロジェクトとなっています。このプロジェクトから実行可能なJarファイルを作成するタスクを作成してください。
なお、メインクラスは `javajo.sample.codic.CodicMain` クラスです。
