= Gradleについて

Gradleは各種作業を自動実行するための基盤ツールです。
プロジェクトの成果物を生成することをビルドとも呼ぶので、ビルドツールとも呼ばれています。

.ビルドとは？
* プロジェクトでの定義により異なるが、目的を達成すること
** jar/warファイルを作るだけにとどまらず、それらをDockerイメージとともにzipで固めてbeanstalkにデプロイするまでを含めてビルドと呼ぶこともできます。
** Rubyプロジェクトのようにコンパイルは必要ない言語においても、アプリケーションとして動作させるために必要な作業(テスト/DBマイグレーション/サーバーへのリリース)もビルドと呼ぶことができます。

ビルドそのものは膨大な作業になるので、それらを構成する小さな単位の作業をタスクと呼びます。

.タスクにはどのようなものがあるか
* タスクには次のようなものがあげられます
** Javaファイルをコンパイルする作業
** リソースファイルから必要な物だけを選別して、一時的なディレクトリーにコピーする作業
** テストを走らせる作業
** テスト結果を集計してまとめる作業
** ...etc

これら膨大なタスクをまとめて実行することも、個々に(タスクを実行するために必要な別のタスクも含めて)実行することも可能にしているのがGradleです。

(mavenでは途中のタスクだけ実行ということができない https://gradle.org/maven_vs_gradle/[Gradleの公式資料：Gradle vs Maven] より)

= ビルドツール

参考ドキュメントは http://amazon.co.jp/o/ASIN/B00PC1JPJE/kkkjkrt-22[Gradle徹底入門]

== Make

ビルドツールの元祖。実行するコマンド、対象ファイル、出力ディレクトリーを定義(configure)して実行するツール。

== Ant

Javaのポイントであるwrite once, run anywhereを実現したプラットフォーム非依存のツール。

* XMLで対象ファイル、出力ディレクトリーなどを定義(configure)して実行するツール。
* シンプルで使いやすく、登場から15年ほど経ても未だに現役で活躍するツール。
* ビルドが大きくなると、XMLファイル自体も大きくなり、XMLファイルの人間との相性の悪さからメンテナンス性が悪く、ビルド職人という職業を作った。
* 依存性の管理機能がなく(後年Ivyによりカバーする)、ライブラリー管理に関してビルド職人を悩ませた。

== Maven

Antの自由度(ゆえの記述量の多さ、標準性のなさ)を規約(convention)により制限し、かつ依存性管理という仕組みを導入してAntの諸々の問題を解決したビルドツール。

* 規約(convention)により、定義(configuration)の記述を排除してビルド定義そのものを読みやすくして、メンテナンス性を向上させた。
* 規約(convention)を覚えなければならず、入門の敷居が高い
* 規約(convention)から外れたことを望んだ途端に、難易度があがってしまう
* XMLで記述するため、人間が読むには辛いところがある(反面、マシンにとっては読み取りやすいため、IDEのサポートが強力(IntelliJ IDEAを見ている限り…))。
* 最近では枯れた技術となり、Spring Boot用のプラグインはGradleのプラグインよりも高機能である。

== その他

Scala用のsbtとかClojure用のLeiningenなどがありますが、それらの言語をやらないので詳しく知りません。

= Gradleの魅力

私見ですが、Gradleの魅力は次の点にあると考えています。

* Mavenの仕組みを活用した楽なビルド
* Antのように自由度が高い
* マルチプロジェクトにも柔軟に対応
* XMLではないので読みやすい
* プリントデバッグできる
** エラーがあっても何が問題なのか指摘してくれる
* Gradle wrapperによってチームで同じビルド環境を共有できる
* 他のJavaアプリケーションの中に組み込むこと(embedded)も可能
