= テキストファイルを書き出す

タスクの作り方をここまで学習してきたので、次にテキストファイルを出力するようなタスクを作っていきます。

`javajo-gradle/task-projects/output-text` ディレクトリーに移動してください。

== `project.file` メソッド

`File` を指定するために、Javaでは(Groovyでも)、 `new File(fileName)` とコンストラクターを呼びます。
Gradleのスクリプトの中でも、この記法は有効ですが、あまり推奨できません。
その代わりにプロジェクトからの相対パスを指定して `File` インスタンスを生成する `project.file` メソッドを使います。

== テキストを書き出すタスク

テキストファイルに書き出すタスクは次のように書くことができます。

[source,groovy]
----
task firstText {
  doLast {
    file('first-text.txt').write('contents', 'UTF-8')
  }
}
----

== テキストを読み込むタスク

テキストファイルを読み込むタスクは次のように書くことができます。

[source,groovy]
----
task loadText {
  doLast {
    def text = file('input-text.txt').text
    println text
  }
}
----

== 演習1

`build.gradle` の次のタスクの内容を確認しつつ、それぞれ実行してください。

* `firstText` タスク
* `loadText` タスク

.Groovyのファイル操作
[TIP]
====

Groovyの `java.io.File` にはJDK標準のメソッドの他に便利なメソッドが利用できます。


.java.io.File
|===
|メソッド |戻り値 |引数 |内容

|`write`
|`void`
|`String text`
|ファイルに文字列を書き出す

|`write`
|`void`
|`String text`, `String encoding`
|ファイルに文字列を指定したエンコーディングで書き出す

|`getText`
|`String`
|なし
|ファイルの内容を読み込む

|`getText`
|`String`
|`String encoding`
|指定したエンコーディングでファイルの内容を読み込む

|'<<'
|'void'
|'String'
|ファイル末尾に文字列を追加する
|===

さらに、Groovyではgetter/setterの呼び出しがフィールドアクセスのように簡略化できますので、 `file.text` のような簡単な書き方でファイルの内容を読み込むことができます。

====

== 演習2

`build.gradle` ファイルにプログラミング言語の名前を5つ改行で区切って `languages.txt` というファイルに書き出す `langs` というタスクを作成してください。

.出力例
[source,txt]
----
Java
Groovy
Scala
Python
Ruby
----

.Groovyのコレクション
[TIP]
====

Groovyでは簡単に `java.util.List` 、 `java.util.Map` のインスタンスを作ることができます。

.`java.util.List`
[source,groovy]
----
List<Integer> numbers = [1, 2, 3, 4, 5]
List<String> langs = [
    'Java', 'Groovy',
    'Scala', 'Python',
    'Ruby', 'JavaScript', 'C'
    'C++', 'Objective-C'
]
List<String> empty = []
----

.`java.util.Map`
[source,groovy]
----
Map<String, String> prefectures = [tokyo: '東京', kyoto: '京都', osaka: '大阪']
Map<Integer, String> prefs = [
    12: '千葉', 13: '東京',
    14: '神奈川']
Map<String, String> empty = [:]
----

なお、 `java.util.Set` のインスタンスを作る場合は一工夫が必要です。

.`java.util.Set`
[source, groovy]
----
Set<Integer> numbers = [1, 2, 3, 4, 5] as Set
Set<String> langs = ['Java', 'Groovy', 'Scala'] as Set<String>
----

====

.Groovyのコレクション操作
[TIP]
====

Groovyでは `List` や `Set` などのコレクション操作を簡単にするためのメソッドが用意されています。

.`collect`
* Java SE8の `Stream` でいうところの、 `map` 操作に該当します。

[source,groovy]
----
[1,2,3,4,5].collect {
  it * it
} /* -> [1, 4, 9, 16, 25] */

['Jorge', 'Steve', 'Michael', 'Christine'].collect {
  it.toUpperCase()
} /* -> ['JORGE', 'STEVE', 'MICHAEL', 'CHRISTINE'] */
----

.`findAll`
* Java SE8の `Stream` でいうところの、 `filter` 操作に該当します。

[source,groovy]
----
[1, 2, 3, 4, 5, 6, 7, 8].findAll {
  it > 3 && it % 2 == 0
} /* -> [4, 6, 8] */

['Java', 'Groovy', 'Scala', 'Clojure', 'JRuby'].findAll {
  it.endsWith('a')
} /* -> ['Java', 'Scala'] */
----

.`join`
* Java SE8の `Stream` でいうところの、 `collect(Collectors.joining())` 操作に該当します。

[source,groovy]
----
['Java', 'Groovy', 'Scala', 'Clojure', 'JRuby'].join(', ')
/* -> 'Java, Groovy, Scala, Clojure, JRuby' */
----

====

== 演習3

先ほど出力した `languages.txt` ファイルを読み込み、マークダウンのリスト形式に変換して `languages.md` ファイルに出力する `langsToMd` タスクを `build.gradle` の中に作成してください。

.出力例
[source,groovy]
----
* Java
* Groovy
* Scala
* Python
* Ruby
----

.Groovyの `String` 便利メソッド
[TIP]
====

Groovyの `java.lang.String` が便利になっていることは前にも説明しましたが、コレクション操作のようなことを可能にするメソッドがついています。

[source,text]
----
Java
Groovy
Scala
----

上記の内容を保持した `String` のインスタンス `text` があるとします。これの各行の先頭に `* ` を付与して表示する操作は次のとおりです。

.`eachLine` メソッド
[source,groovy]
----
text.eachLine {
  println "* ${it}"
}
----

.実行結果
[source,text]
----
* Java
* Groovy
* Scala
----

====

== 演習4(結構ハイレベル)

`build.gradle` ファイルに、`javajo-gradle/task-projects/output-text/files` ディレクトリー以下のすべてのファイルの一覧を`all-files.txt` というファイルに書き出すタスク `listAllFiles` タスクを作成してください。

.`file` 系メソッドをもう少し
[TIP]
====

`Project` オブジェクトが提供する `file` 系メソッドには次のようなものがあります。


.`file` 系メソッド
|===
|メソッド名 |戻り値 |引数 |内容

|`file`
|`File`
|`Object path`
|単一の `File` インスタンスを返す

|`files`
|`ConfigurableFileCollection`
|`Object... paths`
|引数に渡されたファイルのリストを返す

|`fileTree`
|`ConfigurableFileTree`
|`Object baseDir`
|与えられたディレクトリーを起点とするファイルツリー(リストとして扱える)
|===

====

== 演習5(ちょっとむずかしい)

`java-projects/normal-project/src` ディレクトリー以下のファイル一覧を `java-projects/normal-project` からの相対パスで `java-sources.txt` ファイルに書き出すタスク `listJavaSources` タスクを作成してください。

.ヒント
* ルートのプロジェクト(`javajo-gradle`)は、プロパティ `rootProject` で参照できます。
* ルートプロジェクトから `java-projects` サブプロジェクトの `normal-project` サブプロジェクトは、 `project(':java-projects:normal-project')` で取得できます。
* 特定のディレクトリー以下のファイル全てを集めるメソッドは `project.fileTree` メソッドです。
