= タスクの入力と出力を定義する

タスクの入力と出力の設定とタスクの `UP-TO-DATE`(既に完了)について学習します。

`task-projects/up-to-date` ディレクトリーに移動してください。

'''

先ほどまでのテキスト出力タスクを実行している時に、間違えてやり直しなどが発生するたびに、 `rm` コマンド(あるいはファインダーからファイル削除あるいはウィンドウからファイル削除)をしていたと思います。

しかし、タスクの出力ファイルを設定しておくことで、下記のコマンドで消すことができるようになります。

[source,bash]
----
./gradlew cleanTaskName
----

== タスクの出力の設定

タスクの出力ファイルの設定は次の二通りで行えます。

.タスクの出力ファイルの設定-1 出力ファイルがひとつの場合は `outputs.file` にファイルのパス文字列もしくは `File` オブジェクトを渡す
[source,groovy]
----
task langs {
  def outputFile = file('languages.txt')
  /* outputs.file で定義する */
  outputs.file outputFile
  doLast {
    def contents = [
        'Java', 'Groovy', 'Scala',
        'Clojure', 'JRuby'
    ].join('\n')
    /* ファイルへの書き出しは必要です */
    outputFile.write(contents, 'UTF-8')
  }
}
----

.タスクの出力ファイルの設定-2 複数の出力ファイルがある場合は `outputs.files` に配列またはコレクションで渡す
[source,groovy]
----
task osAndLang {
  def matrix = ['windows', 'linux', 'osx'].collect {os ->
    ['Java', 'Groovy', 'Scala'].collect {lang ->
      [os: os, lang: lang]
    }
  }.flatten()
  def outputFiles = matrix.collect {
    file("conbination/${it.os}${it.lang}.txt")
  }
  /* 複数のファイルを出力する場合は outputs.files で定義する */
  outputs.files outputFiles
  doLast {
    if (!file('conbination').exists()) {
      file('conbination').mkdirs()
    }
    matrix.each {
      file("conbination/${it.os}${it.lang}.txt")
          .write("${it.os} - ${it.lang}", 'UTF-8')
    }
  }
}
----

'''

この他、特定のディレクトリーにファイルを出力する場合に用いる `outputs.dir` というメソッドもあります。

=== 演習1

. `task-projects/up-to-date` ディレクトリーに移動して、上記の `langs` タスク、 `osAndLang` タスクを実行してください。
** それぞれ `outputs.file` もしくは `outputs.files` で指定したファイルが出力されていることを確認して下さい。
. `cleanLangs` と `cleanOsAndLang` タスクを実行してください。
** 1.で作成されたファイルが削除されていることを確認して下さい。

== タスクの入力の設定

タスクの入力の設定には複数の方法がありますので、2つほど紹介します。

.タスクの入力の設定-1 入力ファイルが1つの場合は、 `inputs.file` にファイルへのパス文字列または `File` オブジェクトを渡す
[source,groovy]
----
task showLanguages {
  inputs.file 'language-list.txt'
  doLast {
    println file('language-list.txt').text
  }
}
----

.タスクの入力の設定-2 入力ファイルが複数ある場合は、 `inputs.files` に配列もしくはコレクションで渡す
[source,groovy]
----
task langTypes {
  def dir = "${projectDir}/"
  inputs.files fileTree('langs')
  doLast {
    fileTree('langs').collect {
      "${it}".replace(dir, '')
    }.each {
      println it
    }
  }
}
----

'''

この他に、特定のディレクトリー以下のファイルを入力ファイルとする場合に用いる `inputs.dir` というメソッドもあります。

=== 演習2

. ファイル書き出しの演習2でやったプログラミング言語を5つ改行区切りで `5-langs.txt` というファイルに出力する `fiveLangs` タスクを作ってください。
** タスクの出力ファイルとして `5-langs.txt` を設定すること
. ファイル書き出しの演習3でやったように1.で作成した `5-langs.txt` をマークダウン形式に変換して `5-langs.md` というファイルに出力する `fiveLangsToMd` というタスクを作ってください。
** タスクの入力ファイルとして `5-langs.txt` を設定すること
** タスクの出力ファイルとして `5-langs.md` を設定すること
